"""
Your chance to explore Loops and Turtles!

Authors: David Mutchler, Dave Fisher, Valerie Galluzzi, Amanda Stouder,
         their colleagues and Tyler McCormick.
"""
########################################################################
# Done: 1.
# On Line 5 above, replace  PUT_YOUR_NAME_HERE  with your own name.
########################################################################

########################################################################
# TODO: 2.
#
#  You should have RUN the PREVIOUS module and READ its code.
#  (Do so now if you have not already done so.)
#
#  Below this comment, add ANY CODE THAT YOUR WANT, as long as:
#    1. You construct at least 2 rg.SimpleTurtle objects.
#    2. Each rg.SimpleTurtle object draws something
#         (by moving, using its rg.Pen).  ANYTHING is fine!
#    3. Each rg.SimpleTurtle moves inside a LOOP.
#
#  Be creative!  Strive for way-cool pictures!  Abstract pictures rule!
#
#  If you make syntax (notational) errors, no worries -- get help
#  fixing them at either this session OR at the NEXT session.
#
#  Don't forget to COMMIT your work by using  VCS ~ Commit and Push.
########################################################################
import rosegraphics as rg

window = rg.TurtleWindow()

Donatello = rg.SimpleTurtle('turtle')
Donatello.pen = rg.Pen('purple', 5)
Donatello.speed = 30
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)
Donatello.forward(5)
Donatello.left(5)

Raphael = rg.SimpleTurtle('turtle')
Raphael.pen = rg.Pen('red', 5)
Raphael.speed = 30
Raphael.left(90)
Raphael.forward(150)
Raphael.right(120)
Raphael.forward(50)
Raphael.right(120)
Raphael.forward(200)
Raphael.left(150)
Raphael.forward(100)

window.close_on_mouse_click()
